### ISSUE TITLE
[Question] How do I use /calcCoverage

### ISSUE THREAD

**Issue by Ryu945** [apertium/apertium-stats-service#69]
I was told to use /calcCoverage, I need to have apertium-stats-service installed.   The wiki gives to use port 2737 while the having this installed as a separate container shows port 8000.   I am trying to figure out if there is a way to install this inside of Apertium-APY or is the wiki in error and I need to run this as a separate service.  Thus I have  a service for /translate and a service for /calcCoverage which both need all language libraries downloaded.

**Comment by sushain97** [comment]
What? APy's /calcCoverage has nothing to do with stats service.
