### ISSUE TITLE
Docker image builds and runs dev

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/apertium-stats-service#71]
Continuing from https://github.com/apertium/apertium-init/issues/51 because issues is not a discussion board. Also please just come on IRC again...

It seems that the step `RUN cargo build --release` is unused. When the image is run, it will build 353 packages and run the `dev` version, not the release version. This is not ok. The image should be ready to go as-is - we can't wait several minutes for it to start.

Adding `RUN cargo build` at the end works around this, but it's still running dev - shouldn't it run release?

This is all running on Torro now. You have access to the Torro docs to see where and how it's run.

But this all ran before as well. The service started, requests went to it, you could browse the API live, but it returned nothing useful.

**Comment by sushain97** [comment]
> Also please just come on IRC again...

Joined!

> Adding RUN cargo build at the end works around this, but it's still running dev - shouldn't it run release?

Fixed in c4e0e579a2e6ceaee6fa7bc952c710ba71d8e28d.

> but it returned nothing useful.

It's hard for me understand what exactly you mean (do you have an error message or something?) but I suspect this was the issue: 4047e82e6330148f75c1ab5fddcb1dad0503adf8
